# Form implementation generated from reading ui file 'frontpage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 519)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 621, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 130, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 220, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 290, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 360, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(880, 160, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 230, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(880, 310, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(880, 380, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(480, 220, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(480, 300, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 370, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.pushButton.clicked.connect(self.open_LR0_file)
        self.pushButton_2.clicked.connect(self.open_SLR_file)
        self.pushButton_3.clicked.connect(self.open_LR1_file)
        self.pushButton_4.clicked.connect(self.open_LALR_file)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Implementation of Bottom-Up Parsers"))
        self.label_2.setText(_translate("MainWindow", "Team E-1"))
        self.label_3.setText(_translate("MainWindow", "Aira Udaybhasker "))
        self.label_4.setText(_translate("MainWindow", "Popuri Varun Kumar"))
        self.label_5.setText(_translate("MainWindow", "Tangaturu Devendranath Reddy"))
        self.pushButton.setText(_translate("MainWindow", "LR(0)"))
        self.pushButton_2.setText(_translate("MainWindow", "SLR"))
        self.pushButton_3.setText(_translate("MainWindow", "LR(1)"))
        self.pushButton_4.setText(_translate("MainWindow", "LALR"))
        self.label_6.setText(_translate("MainWindow", "BL.EN.U4AIE21005"))
        self.label_7.setText(_translate("MainWindow", "BL.EN.U4AIE21102"))
        self.label_8.setText(_translate("MainWindow", "BL.EN.U4AIE21129"))
        
        
    def open_LR0_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./lr0  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)
                
    def open_SLR_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./SLR  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)
                
    def open_LR1_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./lr1  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)
                
    def open_LALR_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./LALR  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())